### ISSUE TITLE
detours.h error when included from C source file

### ISSUE THREAD

**Issue by dantmnf** [Microsoft/Detours#51]
As it contains some `#ifdef __cplusplus`, I think this should work for both C and C++.

However, 
```
D:\something>cl /Idetours\src /c loader.c
Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27025.1 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

loader.c
detours\src\detours.h(390): error C2071: '__C_ASSERT__': illegal storage class
```
Compiling as C++ resolves this, but this will cause other issues in other C source files.

The assertion was introduced in commit https://github.com/Microsoft/Detours/commit/c238185a26d919e99c4d823255359ffa3b25269d#diff-c220cfbe825e51b1b1eecaaaf610b67cR390
